### PR TITLE
Parity with 0.6.2

### PR DESCRIPTION
**Pull request by ryanartecona**
I have a work project in Ruby I'd like to use docopt.rb for, but the current release of docopt.rb unfortunately won't cut it. Specifically, I need the `options_first` option so I can have subcommands with their own docopt texts (like [docopt/examples/git/git.py](https://github.com/docopt/docopt/blob/master/examples/git/git.py)).

It looks like this project hasn't been touched in quite some time. It's on version 0.5.0, and I don't see any evidence of it ever being tested against the reference testcases.docopt suite.

I've taken the liberty of whipping docopt.rb into shape. With these changes, it is now fully up to parity with docopt at 0.6.2. I've copied the tests & test runner into this repo, and all the cases in testcases.docopt pass.

<details>
<summary>

testcases.docopt failures fixed by these changes</summary>

```
================================= 135: FAILED =================================
r"""usage: prog [-]"""
$ prog -

result> {"-":"-"}

expect> {"-": true}
================================= 136: FAILED =================================
r"""usage: prog [-]"""
$ prog 

result> {"-":null}

expect> {"-": false}
================================= 158: FAILED =================================
r"""usage: prog [options] -a

-a

"""
$ prog -a

result> "user-error"

expect> {"-a": true}
================================= 160: FAILED =================================
r"""usage: prog [-o <o>]...

-o <o>  [default: x]

"""
$ prog 

result> {"-o":"x"}

expect> {"-o": ["x"]}
================================= 162: FAILED =================================
r"""usage: prog [-o <o>]...

-o <o>  [default: x y]

"""
$ prog 

result> {"-o":"x y"}

expect> {"-o": ["x", "y"]}
================================= 164: FAILED =================================
r"""Usage: foo (--xx=x|--yy=y)..."""
$ prog --xx=1 --yy=2

result> {"--xx":["1"],"--yy":[["2"]]}

expect> {"--xx": ["1"], "--yy": ["2"]}
================================== 158 / 164 ==================================
......................................................................................................................................FF.....................F.F.F.F
```

</details>

This also introduces support for `options_first`.

Assuming this repo is still without a maintainer, I hope we at least have someone with rubygems release creds. :)

### CODE REVIEW

**Comment by ryanartecona** [comment]
@keleshev If it helps land these changes, I can step up to be (interim?) maintainer for docopt.rb. Do you or anyone else in the org have rubygems creds for this gem?

**Comment by sadovnik** [comment]
@alexspeller, @johari 👆?

**Comment by alexspeller** [comment]
I have rubygems credentials I think, but no commit access to this repo

**Comment by ryanartecona** [comment]
@alexspeller Just gave you write access to this repo. Feel free to merge and release a version bump if you're up for it and the code looks good.

**Comment by alexspeller** [comment]
@ryanartecona I still don't have write access apparently 

image

**Comment by alexspeller** [comment]
I have reviewed the pull request and the tests are all passing for me, so happy to merge and push a new gem to rubygems if I can get write access.

Also happy to take on maintenance duties if they're relatively light - reviewing PRs, merging and releasing, maybe some minor bugfixes. I don't have much time but I do actually still use docopt myself a bit, so happy to take that on.

**Comment by alexspeller** [comment]
Oh scratch that, I just saw the invitation. Sorting it out now!

**Comment by ryanartecona** [comment]
Thanks a ton @alexspeller!

**Pull request merged**
